---
# tasks file for ansible_molecule_role

# - name: "Create directory for allure"
#   file:
#     path: "{{ allure_dir }}"
#     owner: "{{ allure_dir_user }}"
#     group: "{{ allure_dir_group }}"
#     mode: 0750
#     state: directory

# - name: "Download and unpacking allure-commandline"   
#   unarchive:
#     src: "{{ allure_cmdl_src }}"
#     remote_src: yes
#     dest: "{{ allure_dir }}"
#     keep_newer: yes
#     validate_certs: yes
 
- name: "Ensure python3 and python3-venv is installed"
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - python3
    - python3-venv
    - python3-pip

- name: "Install pytest, allure-pytest and molecule into virtual environment"
  pip: 
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ venv_folder }}"
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
    extra_args: "--upgrade {{ pip_upgrade_packages_list | join(' ') }}"
  loop: "{{ pip_required_packages_list }}"
  vars:
    ansible_python_interpreter: "/usr/bin/python3"